name: app_remedio
description: "A new Flutter project."
publish_to: 'none'
version: 0.3.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.0 # SQLite - Banco de dados
  path: ^1.8.3 # Para manipular caminhos de arquivos
  intl: ^0.20.2 # Internacionalização
  get: ^4.6.6 # Injeção de dependências
  shared_preferences: ^2.2.2 # Para salvar o perfil atual e as configurações
  image_picker: ^1.2.0 # Para selecionar imagens do dispositivo
  path_provider: ^2.1.5 # Para salvar imagens do dispositivo
  local_auth: ^2.1.8 # Biometria - Permite usar a autenticação biométrica/senha do dispositivo
  scrollable_positioned_list: ^0.3.8 # Para a rolagem da lista de datas na tela de agendamentos
  package_info_plus: ^9.0.0
  url_launcher: ^6.2.6 # Para abrir links externos
  share_plus: ^9.0.0 # Para compartilhar textos, imagens e arquivos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/

# Configuração do ícone do launcher
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

# Configuração do splash screen
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#1C1C1E"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#FFFFFF"
    color_dark: "#1C1C1E"
